# Generated by Django 3.0 on 2020-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
