# Generated by Django 3.0 on 2020-01-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20200101_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='access',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
