# Generated by Django 3.0 on 2020-01-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20200101_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='server_id',
            field=models.CharField(default='noid', max_length=30),
            preserve_default=False,
        ),
    ]
