# Generated by Django 3.0 on 2020-01-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_auto_20200102_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.CharField(default='front', max_length=10),
        ),
    ]
