# Generated by Django 3.0 on 2020-01-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cloud.Status'),
            preserve_default=False,
        ),
    ]
