# Generated by Django 3.0 on 2020-01-12 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_proxy_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cloud.Proxy'),
            preserve_default=False,
        ),
    ]
